ALTER TABLE food_records
    ALTER COLUMN calories_kcal TYPE DOUBLE PRECISION USING calories_kcal::DOUBLE PRECISION,
    ALTER COLUMN protein_g     TYPE DOUBLE PRECISION USING protein_g::DOUBLE PRECISION,
    ALTER COLUMN fat_g         TYPE DOUBLE PRECISION USING fat_g::DOUBLE PRECISION,
    ALTER COLUMN carbs_g       TYPE DOUBLE PRECISION USING carbs_g::DOUBLE PRECISION;
